[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/users/*"
  to = "https://nodejs305.dszcbaross.edu.hu/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/recipe/*"
  to = "https://nodejs305.dszcbaross.edu.hu/recipe/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fav/*"
  to = "https://nodejs305.dszcbaross.edu.hu/fav/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://nodejs305.dszcbaross.edu.hu/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200